export const frasesDaSorte : string[] = [
    "Acredite em si mesmo e em tudo que você é. Saiba que há algo dentro de você que é maior do que qualquer obstáculo.",
    "A jornada de mil milhas começa com um único passo.",
    "Não importa o quão devagar você vá, desde que você não pare.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "Você é mais corajoso do que acredita, mais forte do que parece e mais inteligente do que pensa.",
    "A única forma de fazer um ótimo trabalho é amar o que você faz.",
    "Nossa maior fraqueza está em desistir. O caminho mais certo de vencer é tentar mais uma vez.",
    "A vida é 10% o que acontece com a gente e 90% como reagimos a isso.",
    "Seja a mudança que você deseja ver no mundo.",
    "Não importa quem você é ou o que fez, você pode ser quem você quer ser.",
    "Não é o que temos na vida, mas quem temos na vida que importa.",
    "A felicidade não é algo que você adia para o futuro; é algo que você projeta para o presente.",
    "Acredite que você pode e você já está no meio do caminho.",
    "Grandes coisas nunca vêm de zonas de conforto.",
    "Você não falha quando cai; você falha quando permanece no chão.",
    "A paciência é a chave para o sucesso.",
    "Nunca é tarde demais para ser o que você poderia ter sido.",
    "O maior prazer na vida é fazer o que os outros dizem que você não pode fazer.",
    "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso. Se você ama o que faz, terá sucesso.",
    "Não importa o que você decidiu. O que importa é que isso te faz feliz.",
    "Não conte os dias, faça os dias contarem.",
    "O maior risco é não correr riscos. Em um mundo que está mudando rapidamente, a única estratégia que está garantida para falhar é não correr riscos.",
    "A vida é curta demais para desperdiçar com negatividade.",
    "As oportunidades não acontecem. Você as cria.",
    "Seja gentil sempre que possível. E é sempre possível.",
    "O otimismo é a fé que leva à conquista. Nada pode ser feito sem esperança e confiança.",
    "A única maneira de fazer um excelente trabalho é amar o que você faz.",
    "Toda adversidade, todo fracasso, todo coração partido, contém uma lição valiosa. É por isso que o instrutor está sempre quieto durante o teste.",
    "Não importa o quão ocupado você esteja, arranje tempo para fazer o que te deixa feliz.",
    "A única pessoa que você está destinado a se tornar é a pessoa que você decide ser.",
    "Quanto mais difícil a batalha, maior a vitória.",
    "O maior prêmio da vida não é o que você recebe, mas o que você se torna.",
    "Nossas vidas começam a terminar no dia em que permanecemos em silêncio sobre coisas que importam.",
    "Quando uma porta da felicidade se fecha, outra se abre; mas costumamos ficar olhando tanto tempo para a porta fechada que não vemos a que foi aberta para nós.",
    "Acredite em si mesmo e tudo será possível.",
    "Você é mais forte do que pensa e será mais feliz do que imagina.",
    "Acredite que você merece e a coisa mais incrível acontecerá.",
    "Você não é um perdedor até parar de tentar.",
    "Só porque você está lutando não significa que está perdendo.",
    "Se você não puder fazer grandes coisas, faça pequenas coisas de maneira grandiosa.",
    "Sempre parece impossível até que seja feito.",
    "Faça o que puder, com o que você tem, onde estiver.",
    "Comece onde você está. Use o que você tem. Faça o que puder.",
    "Não espere por uma oportunidade. Crie-a.",
    "O maior erro que você pode cometer é o de ficar o tempo todo com medo de cometer algum.",
    "A vida é uma jornada que deve ser viajada calmamente, com compreensão, compaixão e amor.",
    "Seja a mudança que você quer ver no mundo.",
    "A alegria não está nas coisas; está em nós.",
    "Uma atitude positiva pode realmente fazer a diferença na sua vida. Assim, cultive uma atitude positiva.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "Faça o que você pode, com o que você tem, onde você está.",
    "Nossas vidas melhoram apenas quando nós as melhoramos.",
    "Não há elevador para o sucesso, você precisa pegar as escadas.",
    "Não se preocupe em falhar. Preocupe-se com as chances que você perde quando nem sequer tenta.",
    "Você é capaz de mais do que imagina.",
    "Nunca subestime o poder de suas ações. Com um pequeno gesto, você pode mudar a vida de uma pessoa. Para melhor ou para pior. Deus nos coloca onde precisamos estar."]

   export  const frasesDoAzar : string[] = [
    "Ninguém está realmente prestando atenção.",
    "A vida é um jogo em que você sempre perde.",
    "Nada dura para sempre, especialmente sua motivação.",
    "Sabe aquele sonho? É melhor você esquecer.",
    "Se não fosse pelo azar, você não teria sorte nenhuma.",
    "A esperança é como uma bolha de sabão – ela estoura.",
    "Se as coisas puderem piorar, elas definitivamente piorarão.",
    "Talvez você esteja destinado a uma vida de mediocridade. E daí?",
    "Nada vale a pena. Sério, nada.",
    "Você não é um fracasso total, você é apenas um fracasso.",
    "Vai dar errado de qualquer jeito, então por que se preocupar?",
    "Quem precisa de metas quando você pode ficar na cama o dia todo?",
    "A jornada de mil milhas é um desperdício de tempo.",
    "O segredo da vida é não ter expectativas.",
    "Ninguém está torcendo por você. Na verdade, nem mesmo você.",
    "Talvez você esteja destinado a ser uma decepção.",
    "Nada é garantido, exceto a sua inevitável derrota.",
    "Desistir é sempre uma opção válida.",
    "Por que se esforçar quando você pode simplesmente desistir?",
    "Ninguém se importa com o que você faz de qualquer maneira.",
    "Talvez a motivação seja um mito.",
    "Você não vai conseguir. E não tem problema.",
  ];